language: python
cache: pip
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
stages:
  - test
  - flake8
  - name: deploy
    if: tag IS present
install:
  - pip install -r dev-requirements.txt
  - pip install codecov
script: pytest --cov=SimPy
after_success: codecov
jobs:
  include:
  - stage: flake8
    python: 3.6
    install: pip install flake8
    script: flake8 docs
  - stage: deploy
    script: skip
    deploy:
      provider: pypi
      user: "johnguant"
      password:
        secure: OhdWXioLHnDtu8D9u2w1eanmkZ87GVwpr93OL7SQl8mQZ7IB6+gOmRpJKId5w5j1pkO9cmaM/GE07mQt7c4DR5JSfNp2kBnmL81ybr4zn4Zl7t9yIQ7ieJfOYJ9hlxnymnZo8At9b9PlqLbJp1OxJcwZHAMXRGKXrmoPpf/Zarwvd0+gzA9LQQSku5jom6xa9KnCxd9/i+pM1Ov7EW7oiHVyn/H7cHcy/TnZqtU9FUn4qDrkTOkrzEsNdvsfyG//3JMKKXzzu+cMU2eKSY4UhuDXXY1XmupNkbHB9ytuR7t7moGceal9V+pE7jYNKNq83VVmvrdq/z8HJrU5LP02wetBk961eOvFA8jTC898d4qAjMrEBpL86XXMcqpd8eWYzTlz5YfrS5jZFkuOpsteYD9sRgdh/CTiY4te/5HKLLlhgfBThknXW4IdC+FDbHCXVadH4znAa8h1ZedcjYM3JEZooCG1TbSJRIxsmtSx4bFkN+bm9X6cpVhQBdAhErTjj49uH+DLb/cAYi0bZu0tAJSuKP+RBkCaSQ3Ia4fIZCA297mJ250xSyj9w3WI/q21s4bXB/J9JoaHnUplzbiQfYEEQNh0HT77asnTM6GiqZxkoe836uS/wa3elGfCmeeiqdbW4+83YgLptxA2efyX0YEt1xzFvnBkI56E4gtLgkQ=
      on:
        tags: true
      distributions: "sdist bdist_wheel"
