language: python
cache: pip
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
  - pip install -r dev-requirements.txt
  - pip install codecov
script:
  - pytest --cov=SimPy
after_success:
  - codecov
